name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    permissions:
      contents: read
      id-token: write
      pages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm install
          npm run build
          chmod -R 777 dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'github-pages'
          path: 'dist/'
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
